const Cars = [
  {
    id: 1,
    marka: 'Toyota',
    model: 'Camry',
    ban_novu: 'Sedan',
    il: 2021,
    reng: 'Qara',
    yanacaq: 'Benzin',
    oturucu: 'Ön',
    suret_qutusu: 'Avtomat',
    muherrik: '2.5 L',
    at_gucu: 203,
    qiymet: 38500,
    valyuta: 'AZN',
    seher: 'Bakı',
    yurus: '45 000 km',
    kreditdedir: false,
    barter_mumkundur: true,
    elan_tarixi: '2026-03-25',
    sekil: './img/toyota_camry_2021.jpg',
    elave_melumat:
      'Ideal vəziyyətdədir, heç bir detalı dəyişilməyib. Rəsmi servisdən alınıb.',
  },
  {
    id: 2,
    marka: 'BMW',
    model: 'X5',
    ban_novu: 'Offroader / SUV',
    il: 2023,
    reng: 'Ağ',
    yanacaq: 'Dizel',
    oturucu: 'Tam (4WD)',
    suret_qutusu: 'Avtomat',
    muherrik: '3.0 L',
    at_gucu: 286,
    qiymet: 125000,
    valyuta: 'AZN',
    seher: 'Bakı',
    yurus: '18 000 km',
    kreditdedir: true,
    barter_mumkundur: false,
    elan_tarixi: '2026-03-28',
    sekil: '../Cars/img/bmw_x5.jpg',
    elave_melumat:
      'M-Paket, panoramik tavan, zolağa nəzarət sistemi, bezkraska.',
  },
  {
    id: 3,
    marka: 'Mercedes',
    model: 'C 200',
    ban_novu: 'Sedan',
    il: 2019,
    reng: 'Gümüşü',
    yanacaq: 'Hibrid',
    oturucu: 'Arxa',
    suret_qutusu: 'Avtomat',
    muherrik: '1.5 L',
    at_gucu: 184,
    qiymet: 44000,
    valyuta: 'AZN',
    seher: 'Gəncə',
    yurus: '72 000 km',
    kreditdedir: false,
    barter_mumkundur: true,
    elan_tarixi: '2026-03-20',
    sekil: './img/mercedes_c200_2019.jpg',
    elave_melumat:
      'Hec bir problemi yoxdur, yeni təkərlər alınıb, vaxtlı-vaxtında qulluq olunub.',
  },
  {
    id: 4,
    marka: 'Hyundai',
    model: 'Elantra',
    ban_novu: 'Sedan',
    il: 2020,
    reng: 'Göy',
    yanacaq: 'Benzin',
    oturucu: 'Ön',
    suret_qutusu: 'Avtomat',
    muherrik: '2.0 L',
    at_gucu: 147,
    qiymet: 29800,
    valyuta: 'AZN',
    seher: 'Sumqayıt',
    yurus: '60 000 km',
    kreditdedir: false,
    barter_mumkundur: true,
    elan_tarixi: '2026-03-27',
    sekil: './img/hyundai_elantra_2020.jpg',

    elave_melumat: 'Full komplektasiya,start-stop, monitor, arxa kamera.',
  },
  {
    id: 5,
    marka: 'Kia',
    model: 'Sorento',
    ban_novu: 'Offroader / SUV',
    il: 2022,
    reng: 'Tünd Boz',
    yanacaq: 'Dizel',
    oturucu: 'Tam (4WD)',
    suret_qutusu: 'Avtomat',
    muherrik: '2.2 L',
    at_gucu: 199,
    qiymet: 76000,
    valyuta: 'AZN',
    seher: 'Bakı',
    yurus: '35 000 km',
    kreditdedir: true,
    barter_mumkundur: false,
    elan_tarixi: '2026-03-29',
    sekil: './img/kia_sorento_2022.webp ',
    elave_melumat:
      '7 yerlik, 3 cərgə oturacaq, qızdırılan və soyudulan ön oturacaqlar.',
  },
  {
    id: 6,
    marka: 'Lada (VAZ)',
    model: '2107',
    ban_novu: 'Sedan',
    il: 2011,
    reng: 'Albalı',
    yanacaq: 'Benzin',
    oturucu: 'Arxa',
    suret_qutusu: 'Mexaniki',
    muherrik: '1.6 L',
    at_gucu: 75,
    qiymet: 7500,
    valyuta: 'AZN',
    seher: 'Şəki',
    yurus: '140 000 km',
    kreditdedir: false,
    barter_mumkundur: true,
    elan_tarixi: '2026-03-15',
    sekil: './img/vaz_2107_2011.jpg',
    elave_melumat:
      'Bezkraska həvəskarları üçün. Maşın səliqəli sürülüb, qaraj şəraitində saxlanılıb.',
  },
  {
    id: 7,
    marka: 'Nissan',
    model: 'X-Trail',
    ban_novu: 'Offroader / SUV',
    il: 2018,
    reng: 'Qəhvəyi',
    yanacaq: 'Benzin',
    oturucu: 'Tam (4WD)',
    suret_qutusu: 'Variator',
    muherrik: '2.5 L',
    at_gucu: 171,
    qiymet: 35000,
    valyuta: 'AZN',
    seher: 'Bakı',
    yurus: '85 000 km',
    kreditdedir: false,
    barter_mumkundur: true,
    elan_tarixi: '2026-03-26',
    sekil: './img/nissan_xtrail_2018.jpg',
    elave_melumat: 'Panoramik lyuk, dəri salon, 360 dərəcə kamera.',
  },
  {
    id: 8,
    marka: 'Chevrolet',
    model: 'Cruze',
    ban_novu: 'Sedan',
    il: 2017,
    reng: 'Qırmızı',
    yanacaq: 'Benzin',
    oturucu: 'Ön',
    suret_qutusu: 'Avtomat',
    muherrik: '1.4 L (Turbo)',
    at_gucu: 153,
    qiymet: 20500,
    valyuta: 'AZN',
    seher: 'Gəncə',
    yurus: '110 000 km',
    kreditdedir: false,
    barter_mumkundur: false,
    elan_tarixi: '2026-03-18',
    sekil: './img/Chevrolet.jpg',
    elave_melumat: 'RS Dizayn, böyük sensor ekran, Apple CarPlay dəstəyi.',
  },
  {
    id: 9,
    marka: 'Range Rover',
    model: 'Sport',
    ban_novu: 'Offroader / SUV',
    il: 2021,
    reng: 'Qara',
    yanacaq: 'Dizel',
    oturucu: 'Tam (4WD)',
    suret_qutusu: 'Avtomat',
    muherrik: '3.0 L',
    at_gucu: 300,
    qiymet: 145000,
    valyuta: 'AZN',
    seher: 'Bakı',
    yurus: '50 000 km',
    kreditdedir: false,
    barter_mumkundur: true,
    elan_tarixi: '2026-03-29',
    sekil: './img/range_rover_sport_2021.jpg',
    elave_melumat: 'Autobiography paket, Meridian səs sistemi, pnevma asqı.',
  },
  {
    id: 10,
    marka: 'Hyundai',
    model: 'Sonata',
    ban_novu: 'Sedan',
    il: 2015,
    reng: 'Ağ',
    yanacaq: 'Benzin',
    oturucu: 'Ön',
    suret_qutusu: 'Avtomat',
    muherrik: '2.4 L',
    at_gucu: 185,
    qiymet: 24500,
    valyuta: 'AZN',
    seher: 'Lənkəran',
    yurus: '125 000 km',
    kreditdedir: false,
    barter_mumkundur: true,
    elan_tarixi: '2026-03-12',
    sekil: './img/hyundai_sonata_2015.jpg',
    elave_melumat:
      'Kondisioner işləkdir, oturacaq qızdırıcılar, yüngül lehimli disklər.',
  },
  {
    id: 11,
    marka: 'Volkswagen',
    model: 'Passat',
    ban_novu: 'Sedan',
    il: 2019,
    reng: 'Boz',
    yanacaq: 'Dizel',
    oturucu: 'Ön',
    suret_qutusu: 'Avtomat',
    muherrik: '2.0 L',
    at_gucu: 150,
    qiymet: 39000,
    valyuta: 'AZN',
    seher: 'Bakı',
    yurus: '88 000 km',
    kreditdedir: false,
    barter_mumkundur: false,
    elan_tarixi: '2026-03-24',
    sekil: './img/vw_passat_2019.jpg',
    elave_melumat: 'Avropa istehsalı, LED faralar, virtual pribor panel.',
  },
  {
    id: 12,
    marka: 'Lexus',
    model: 'RX 350',
    ban_novu: 'Offroader / SUV',
    il: 2020,
    reng: 'Qara',
    yanacaq: 'Benzin',
    oturucu: 'Tam (4WD)',
    suret_qutusu: 'Avtomat',
    muherrik: '3.5 L',
    at_gucu: 295,
    qiymet: 88000,
    valyuta: 'AZN',
    seher: 'Bakı',
    yurus: '55 000 km',
    kreditdedir: false,
    barter_mumkundur: true,
    elan_tarixi: '2026-03-28',
    sekil: './img/lexus_rx350_2020.jpg',
    elave_melumat:
      'F-Sport komplektasiya, Mark Levinson səs sistemi, kor zona sensoru.',
  },
  {
    id: 13,
    marka: 'Ford',
    model: 'Fusion',
    ban_novu: 'Sedan',
    il: 2018,
    reng: 'Tünd Göy',
    yanacaq: 'Benzin',
    oturucu: 'Ön',
    suret_qutusu: 'Avtomat',
    muherrik: '1.5 L (Turbo)',
    at_gucu: 181,
    qiymet: 23000,
    valyuta: 'AZN',
    seher: 'Sumqayıt',
    yurus: '95 000 km',
    kreditdedir: false,
    barter_mumkundur: true,
    elan_tarixi: '2026-03-22',
    sekil: './img/ford_fusion_2018.jpg',
    elave_melumat: 'SE paket, açarsız daxil olma, kodlu qapı kilidi.',
  },
  {
    id: 14,
    marka: 'Porsche',
    model: 'Cayenne',
    ban_novu: 'Offroader / SUV',
    il: 2022,
    reng: 'Ağ',
    yanacaq: 'Benzin',
    oturucu: 'Tam (4WD)',
    suret_qutusu: 'Avtomat',
    muherrik: '3.0 L',
    at_gucu: 340,
    qiymet: 165000,
    valyuta: 'AZN',
    seher: 'Bakı',
    yurus: '25 000 km',
    kreditdedir: false,
    barter_mumkundur: false,
    elan_tarixi: '2026-03-30',
    sekil: './img/porsche_cayenne_2022.jpg',
    elave_melumat: 'Sport Chrono paket, 21 düymlük disklər, Bose audio sistem.',
  },
  {
    id: 15,
    marka: 'Kia',
    model: 'Optima',
    ban_novu: 'Sedan',
    il: 2016,
    reng: 'Gümüşü',
    yanacaq: 'Benzin',
    oturucu: 'Ön',
    suret_qutusu: 'Avtomat',
    muherrik: '2.4 L',
    at_gucu: 185,
    qiymet: 25000,
    valyuta: 'AZN',
    seher: 'Mingəçevir',
    yurus: '115 000 km',
    kreditdedir: false,
    barter_mumkundur: true,
    elan_tarixi: '2026-03-14',
    sekil: './img/kia_optima_2016.jpg',
    elave_melumat: 'Panoramik dam, yaddaşlı oturacaqlar, arxa parkinq radarı.',
  },
]

export default Cars
